### ISSUE TITLE
How to compile plugin cs to dll?

### ISSUE THREAD

**Issue by Mezir** [Splamy/TS3AudioBot#803]
How to compile plugin cs to dll?
https://i.imgur.com/yi2M7Gz.png

**Comment by Splamy** [comment]
For plugins you should not add files to the audiobot project, you don't even need to download the audiobot source.
Instead, create a new solution and add a netcoreapp3.1 library project. Add the ts3audiobot.dll (and the TSLib if needed) to the references.
Paste the bare minimum for a plugin (see our wiki) into your main cs file.
Now you can click on build in VS and will create a binary in bin/(Debug or Release)/yourplugin.dll

**Comment by Mezir** [comment]
@Splamy thanks. :)

**Comment by zumoshi** [comment]
@Splamy 
The instructions work fine for the latest release and the Master branch. But I'm having trouble getting it to work on the develop branch. It compiles fine but I get this error on the console every time an `AsyncEventHandler` is called:

```
19:14:38.7674|ERROR|0| Unexpected command error: Could not load file or assembly 'System.Threading.Tasks, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```

Repro:
```bash
cd ~
git clone https://github.com/Splamy/TS3AudioBot.git
cd TS3AudioBot/ && git checkout develop
dotnet build
cd ~
mkdir test && cd test
dotnet new classlib -f netcoreapp3.1
cp ~/TS3AudioBot/TS3AudioBot/bin/Debug/netcoreapp3.1/TSLib.dll .
cp ~/TS3AudioBot/TS3AudioBot/bin/Debug/netcoreapp3.1/TS3AudioBot.dll .
```
Edit `test.csproj`:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="TS3AudioBot">
      <HintPath>.\TS3AudioBot.dll</HintPath>
    </Reference>
    <Reference Include="TSLib">
      <HintPath>.\TSLib.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
```
Edit `Class1.cs`:
```csharp
using System;
using System.Threading.Tasks;
using TS3AudioBot.Audio;
using TS3AudioBot.Plugins;

public class Class1 : IBotPlugin
{
    private PlayManager playManager;

    public Class1(PlayManager playManager)
    {
        this.playManager = playManager;
    }

    public void Dispose()
    {
        playManager.AfterResourceStarted -= PlayManagerOnAfterResourceStarted;
    }

    public void Initialize()
    {
        playManager.AfterResourceStarted += PlayManagerOnAfterResourceStarted;
    }

    private async Task PlayManagerOnAfterResourceStarted(object sender, PlayInfoEventArgs value)
    {
        Console.WriteLine("Playing");
    }
}
```
Run `dotnet build` and copy `/bin/Debug/netcoreapp3.1/test.dll` to `plugins` directory of a Freshly extracted instance from https://splamy.de/Nightly#ts3ab
Run the bot and play any link after loading the plugin.

Expected behavior: Bot will print `Playing` in the console.
Actual behavior:
```
<23:48:22> "TS3AudioBot": An unexpected error occurred: Could not load file or assembly 'System.Threading.Tasks, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```
```
20:17:50.9808| INFO|Core| Client connected.
20:17:53.1698| INFO|0| User bor requested: !plugins list
20:17:55.1508| INFO|0| User bor requested: !plugins load 0
20:18:06.0738| INFO|0| User bor requested: !play [URL]http://af4ae594ba13.ngrok.io/test.mp3[/URL]
20:18:08.8680|ERROR|0| Unexpected command error: Could not load file or assembly 'System.Threading.Tasks, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

20:18:08.9439| WARN|0| file_not_found: the command failed to execute: file not found
```

The same code as a `.cs` file works as expected.
The issue seems to be because the compiled version uses `System.Runtime Version=4.2.2.0` while the `dotnet-sdk-3.1` package in ubuntu compiles with `4.1.2.0`. Part of detailed verbosity output of compiler:
```
 Dependency "System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
             Could not resolve this reference. Could not locate the assembly "System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
                 For SearchPath "{CandidateAssemblyFiles}".
                 Considered "TS3AudioBot.dll",
                                but its name "TS3AudioBot"
                                didn't match the expected name "System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
                 Considered "TSLib.dll",
                                but its name "TSLib"
                                didn't match the expected name "System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
             Required by "TS3AudioBot".
             Required by "TSLib".
```

I got the same result from VisualStudio but decided to try it with the Linux command line to make sure it wasn't caused by windows 8.1 (I haven't upgraded to 10 yet)
I didn't open a new issue because this is mostly a question, not a bug. Sorry for bothering you but I ran out of things to try.

**Comment by zumoshi** [comment]
It seems the standalone version that the build system creates has no reference to `System.Threading.Tasks` while the version I compiled had. I figured this out by comparing the references of the dll file extracted when running the standalone version (from `C:\Users\Bor\AppData\Local\Temp\.net\TS3AudioBot\m0uupssv.ive`) with the version compiled from the develop branch using `dotnet-sdk-3.1` inside dotPeek.

Since I was referencing my dll files for compiling the plugin then running it against your compiled version It was having trouble finding `System.Threading.Tasks`.

Compiling it against your version yields this compile error:
```
root@ubuntu:~/t/plugin# docker run -v $(pwd):/proj--rm mcr.microsoft.com/dotnet/core/sdk:3.1 dotnet build /proj
Microsoft (R) Build Engine version 16.7.0+7fb82e5b2 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /proj/RepeatOnFail.csproj (in 198 ms).
/usr/share/dotnet/sdk/3.1.403/Microsoft.Common.CurrentVersion.targets(2084,5): warning MSB3277: Found conflicts between different versions of "System.Text.Json" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [/proj/RepeatOnFail.csproj]
RepeatOnFail.cs(7,14): error CS0012: The type 'IDisposable' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. [/proj/RepeatOnFail.csproj]
RepeatOnFail.cs(7,29): error CS0012: The type 'IDisposable' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. [/proj/RepeatOnFail.csproj]

Build FAILED.

/usr/share/dotnet/sdk/3.1.403/Microsoft.Common.CurrentVersion.targets(2084,5): warning MSB3277: Found conflicts between different versions of "System.Text.Json" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [/proj/RepeatOnFail.csproj]
RepeatOnFail.cs(7,14): error CS0012: The type 'IDisposable' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. [/proj/RepeatOnFail.csproj]
RepeatOnFail.cs(7,29): error CS0012: The type 'IDisposable' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. [/proj/RepeatOnFail.csproj]
    1 Warning(s)
    2 Error(s)

Time Elapsed 00:00:02.65
```
Any idea why the automated nightly build references `System.Private.CoreLib` instead of `System.Threading.Tasks`?
